apiVersion: magic.cloudflare.crossplane.io/v1alpha1
kind: NetworkMonitoringConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: magic/v1alpha1/networkmonitoringconfiguration
  labels:
    testing.upbound.io/example-name: example_magic_network_monitoring_configuration
  name: example-magic-network-monitoring-configuration
spec:
  forProvider:
    accountId: 6f91088a406011ed95aed352566e8d4c
    defaultSampling: 1
    routerIps:
    - 203.0.113.1
    warpDevices:
    - id: 5360368d-b351-4791-abe1-93550dabd351
      name: My warp device
      routerIp: 203.0.113.1
