apiVersion: magic.cloudflare.crossplane.io/v1alpha1
kind: TransitSiteLan
metadata:
  annotations:
    meta.upbound.io/example-id: magic/v1alpha1/transitsitelan
  labels:
    testing.upbound.io/example-name: example_magic_transit_site_lan
  name: example-magic-transit-site-lan
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    haLink: true
    nat:
      staticPrefix: 192.0.2.0/24
    physport: 1
    routedSubnets:
    - nat:
        staticPrefix: 192.0.2.0/24
      nextHop: 192.0.2.1
      prefix: 192.0.2.0/24
    siteId: 023e105f4ecef8ad9ca31a8372d0c353
    staticAddressing:
      address: 192.0.2.0/24
      dhcpRelay:
        serverAddresses:
        - 192.0.2.1
      dhcpServer:
        dhcpPoolEnd: 192.0.2.1
        dhcpPoolStart: 192.0.2.1
        dnsServer: 192.0.2.1
        dnsServers:
        - 192.0.2.1
        reservations:
          "00:11:22:33:44:55": 192.0.2.100
          AA:BB:CC:DD:EE:FF: 192.168.1.101
      secondaryAddress: 192.0.2.0/24
      virtualAddress: 192.0.2.0/24
    vlanTag: 0
