apiVersion: magic.cloudflare.crossplane.io/v1alpha1
kind: WanGreTunnel
metadata:
  annotations:
    meta.upbound.io/example-id: magic/v1alpha1/wangretunnel
  labels:
    testing.upbound.io/example-name: example_magic_wan_gre_tunnel
  name: example-magic-wan-gre-tunnel
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
