// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MetadataInitParameters struct {

	// (String) Main module name of uploaded snippet
	// Main module name of uploaded snippet
	MainModule *string `json:"mainModule,omitempty" tf:"main_module,omitempty"`
}

type MetadataObservation struct {

	// (String) Main module name of uploaded snippet
	// Main module name of uploaded snippet
	MainModule *string `json:"mainModule,omitempty" tf:"main_module,omitempty"`
}

type MetadataParameters struct {

	// (String) Main module name of uploaded snippet
	// Main module name of uploaded snippet
	// +kubebuilder:validation:Optional
	MainModule *string `json:"mainModule,omitempty" tf:"main_module,omitempty"`
}

type SnippetsInitParameters struct {

	// (String) Content files of uploaded snippet
	// Content files of uploaded snippet
	Files *string `json:"files,omitempty" tf:"files,omitempty"`

	// (Attributes) (see below for nested schema)
	Metadata *MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Snippet identifying name
	// Snippet identifying name
	SnippetName *string `json:"snippetName,omitempty" tf:"snippet_name,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type SnippetsObservation struct {

	// (String) Creation time of the snippet
	// Creation time of the snippet
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String) Content files of uploaded snippet
	// Content files of uploaded snippet
	Files *string `json:"files,omitempty" tf:"files,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) (see below for nested schema)
	Metadata *MetadataObservation `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Modification time of the snippet
	// Modification time of the snippet
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// (String) Snippet identifying name
	// Snippet identifying name
	SnippetName *string `json:"snippetName,omitempty" tf:"snippet_name,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type SnippetsParameters struct {

	// (String) Content files of uploaded snippet
	// Content files of uploaded snippet
	// +kubebuilder:validation:Optional
	Files *string `json:"files,omitempty" tf:"files,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String) Snippet identifying name
	// Snippet identifying name
	// +kubebuilder:validation:Optional
	SnippetName *string `json:"snippetName,omitempty" tf:"snippet_name,omitempty"`

	// (String) Identifier
	// Identifier
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

// SnippetsSpec defines the desired state of Snippets
type SnippetsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SnippetsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SnippetsInitParameters `json:"initProvider,omitempty"`
}

// SnippetsStatus defines the observed state of Snippets.
type SnippetsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SnippetsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Snippets is the Schema for the Snippetss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare-upjet}
type Snippets struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.snippetName) || (has(self.initProvider) && has(self.initProvider.snippetName))",message="spec.forProvider.snippetName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   SnippetsSpec   `json:"spec"`
	Status SnippetsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SnippetsList contains a list of Snippetss
type SnippetsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Snippets `json:"items"`
}

// Repository type metadata.
var (
	Snippets_Kind             = "Snippets"
	Snippets_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Snippets_Kind}.String()
	Snippets_KindAPIVersion   = Snippets_Kind + "." + CRDGroupVersion.String()
	Snippets_GroupVersionKind = CRDGroupVersion.WithKind(Snippets_Kind)
)

func init() {
	SchemeBuilder.Register(&Snippets{}, &SnippetsList{})
}
