apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: CacheReserve
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/cachereserve
  labels:
    testing.upbound.io/example-name: example_zone_cache_reserve
  name: example-zone-cache-reserve
spec:
  forProvider:
    value: "on"
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
