apiVersion: r2.cloudflare.crossplane.io/v1alpha1
kind: BucketLifecycle
metadata:
  annotations:
    meta.upbound.io/example-id: r2/v1alpha1/bucketlifecycle
  labels:
    testing.upbound.io/example-name: example_r2_bucket_lifecycle
  name: example-r2-bucket-lifecycle
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    bucketName: example-bucket
    rules:
    - abortMultipartUploadsTransition:
        condition:
          maxAge: 0
          type: Age
      conditions:
        prefix: prefix
      deleteObjectsTransition:
        condition:
          maxAge: 0
          type: Age
      enabled: true
      id: Expire all objects older than 24 hours
      storageClassTransitions:
      - condition:
          maxAge: 0
          type: Age
        storageClass: InfrequentAccess
