apiVersion: r2.cloudflare.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: r2/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: example_r2_bucket
  name: example-r2-bucket
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    location: apac
    storageClass: Standard
