apiVersion: cloudflare.cloudflare.crossplane.io/v1alpha1
kind: Filter
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/filter
  labels:
    testing.upbound.io/example-name: example_filter
  name: example-filter
spec:
  forProvider:
    expression: (http.request.uri.path ~ ".*wp-login.php" or http.request.uri.path
      ~ ".*xmlrpc.php") and ip.addr ne 172.16.22.155
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
