apiVersion: cloudflare.cloudflare.crossplane.io/v1alpha1
kind: Healthcheck
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/healthcheck
  labels:
    testing.upbound.io/example-name: example_healthcheck
  name: example-healthcheck
spec:
  forProvider:
    address: www.example.com
    checkRegions:
    - WNAM
    - ENAM
    consecutiveFails: 0
    consecutiveSuccesses: 0
    description: Health check for www.example.com
    httpConfig:
      allowInsecure: true
      expectedBody: success
      expectedCodes:
      - 2xx
      - "302"
      followRedirects: true
      header:
        Host:
        - example.com
        X-App-ID:
        - abc123
      method: GET
      path: /health
      port: 0
    interval: 0
    retries: 0
    suspended: true
    tcpConfig:
      method: connection_established
      port: 0
    timeout: 0
    type: HTTPS
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
