apiVersion: cloudflare.cloudflare.crossplane.io/v1alpha1
kind: Ruleset
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/ruleset
  labels:
    testing.upbound.io/example-name: example_ruleset
  name: example-ruleset
spec:
  forProvider:
    description: My ruleset to execute managed rulesets
    kind: managed
    phase: ddos_l4
    rules:
    - action: block
      actionParameters:
        response:
          content: |2
                    {
                      "success": false,
                      "error": "you have been blocked"
                    }
          contentType: application/json
          statusCode: 400
      description: Block when the IP address is not 1.1.1.1
      enabled: true
      exposedCredentialCheck:
        passwordExpression: url_decode(http.request.body.form[\"password\"][0])
        usernameExpression: url_decode(http.request.body.form[\"username\"][0])
      expression: ip.src ne 1.1.1.1
      logging:
        enabled: true
      ratelimit:
        characteristics:
        - ip.src
        countingExpression: http.request.body.raw eq "abcd"
        mitigationTimeout: 600
        period: 10
        requestsPerPeriod: 1000
        requestsToOrigin: true
        scorePerPeriod: 400
        scoreResponseHeaderName: my-score
      ref: my_ref
    zoneId: zone_id
