apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustDlpCustomProfile
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustdlpcustomprofile
  labels:
    testing.upbound.io/example-name: example_zero_trust_dlp_custom_profile
  name: example-zero-trust-dlp-custom-profile
spec:
  forProvider:
    accountId: account_id
    profiles:
    - aiContextEnabled: true
      allowedMatchCount: 5
      confidenceThreshold: confidence_threshold
      contextAwareness:
        enabled: true
        skip:
          files: true
      description: description
      entries:
      - enabled: true
        name: name
        pattern:
          regex: regex
          validation: luhn
      name: name
      ocrEnabled: true
      sharedEntries:
      - enabled: true
        entryId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
        entryType: custom
