apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustAccessMtlsHostnameSettings
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustaccessmtlshostnamesettings
  labels:
    testing.upbound.io/example-name: example_zero_trust_access_mtls_hostname_settings
  name: example-zero-trust-access-mtls-hostname-settings
spec:
  forProvider:
    settings:
    - chinaNetwork: false
      clientCertificateForwarding: true
      hostname: admin.example.com
    zoneId: zone_id
