apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustDeviceDefaultProfile
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustdevicedefaultprofile
  labels:
    testing.upbound.io/example-name: example_zero_trust_device_default_profile
  name: example-zero-trust-device-default-profile
spec:
  forProvider:
    accountId: 699d98642c564d2e855e9661899b7252
    allowModeSwitch: true
    allowUpdates: true
    allowedToLeave: true
    autoConnect: 0
    captivePortal: 180
    disableAutoFallback: true
    excludeOfficeIps: true
    serviceModeV2:
      mode: proxy
      port: 3000
    supportUrl: https://1.1.1.1/help
    switchLocked: true
    tunnelProtocol: wireguard
