apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustAccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustaccesspolicy
  labels:
    testing.upbound.io/example-name: example_zero_trust_access_policy
  name: example-zero-trust-access-policy
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    approvalGroups:
    - approvalsNeeded: 1
      emailAddresses:
      - test1@cloudflare.com
      - test2@cloudflare.com
      emailListUuid: email_list_uuid
    - approvalsNeeded: 3
      emailAddresses:
      - test@cloudflare.com
      - test2@cloudflare.com
      emailListUuid: 597147a1-976b-4ef2-9af0-81d5d007fc34
    approvalRequired: true
    decision: allow
    exclude:
    - group:
        id: aa0a4aab-672b-4bdb-bc33-a59f1130a11f
    include:
    - group:
        id: aa0a4aab-672b-4bdb-bc33-a59f1130a11f
    isolationRequired: false
    purposeJustificationPrompt: Please enter a justification for entering this protected
      domain.
    purposeJustificationRequired: true
    require:
    - group:
        id: aa0a4aab-672b-4bdb-bc33-a59f1130a11f
    sessionDuration: 24h
