apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustGatewayPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustgatewaypolicy
  labels:
    testing.upbound.io/example-name: example_zero_trust_gateway_policy
  name: example-zero-trust-gateway-policy
spec:
  forProvider:
    accountId: 699d98642c564d2e855e9661899b7252
    action: "on"
    description: Block bad websites based on their host name.
    devicePosture: any(device_posture.checks.passed[*] in {"1308749e-fcfb-4ebc-b051-fe022b632644"})
    enabled: true
    expiration:
      duration: 10
      expired: false
      expiresAt: "2014-01-01T05:20:20Z"
    filters:
    - http
    identity: any(identity.groups.name[*] in {"finance"})
    precedence: 0
    ruleSettings:
      addHeaders:
        foo: string
      allowChildBypass: false
      auditSsh:
        commandLogging: false
      bisoAdminControls:
        copy: enabled
        dcp: false
        dd: false
        dk: false
        download: enabled
        dp: false
        du: false
        keyboard: enabled
        paste: enabled
        printing: enabled
        upload: enabled
        version: v1
      blockPageEnabled: true
      blockReason: This website is a security risk
      bypassParentRule: false
      checkSession:
        duration: 300s
        enforce: true
      dnsResolvers:
        ipv4:
        - ip: 2.2.2.2
          port: 5053
          routeThroughPrivateNetwork: true
          vnetId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
        ipv6:
        - ip: '2001:DB8::'
          port: 5053
          routeThroughPrivateNetwork: true
          vnetId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      egress:
        ipv4: 192.0.2.2
        ipv4Fallback: 192.0.2.3
        ipv6: 2001:DB8::/64
      ignoreCnameCategoryMatches: true
      insecureDisableDnssecValidation: false
      ipCategories: true
      ipIndicatorFeeds: true
      l4override:
        ip: 1.1.1.1
        port: 0
      notificationSettings:
        enabled: true
        msg: msg
        supportUrl: support_url
      overrideHost: example.com
      overrideIps:
      - 1.1.1.1
      - 2.2.2.2
      payloadLog:
        enabled: true
      quarantine:
        fileTypes:
        - exe
      resolveDnsInternally:
        fallback: none
        viewId: view_id
      resolveDnsThroughCloudflare: true
      untrustedCert:
        action: pass_through
    schedule:
      fri: 08:00-12:30,13:30-17:00
      mon: 08:00-12:30,13:30-17:00
      sat: 08:00-12:30,13:30-17:00
      sun: 08:00-12:30,13:30-17:00
      thu: 08:00-12:30,13:30-17:00
      timeZone: America/New York
      tue: 08:00-12:30,13:30-17:00
      wed: 08:00-12:30,13:30-17:00
    traffic: http.request.uri matches ".*a/partial/uri.*" and http.request.host in
      $01302951-49f9-47c9-a400-0297e60b6a10
