apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustAccessIdentityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustaccessidentityprovider
  labels:
    testing.upbound.io/example-name: example_zero_trust_access_identity_provider
  name: example-zero-trust-access-identity-provider
spec:
  forProvider:
    config:
      claims:
      - email_verified
      - preferred_username
      - custom_claim_name
      clientId: <your client id>
      clientSecret: <your client secret>
      conditionalAccessEnabled: true
      directoryId: <your azure directory uuid>
      emailClaimName: custom_claim_name
      prompt: login
      supportGroups: true
    scimConfig:
      enabled: true
      identityUpdateBehavior: automatic
      seatDeprovision: true
      userDeprovision: true
    type: onetimepin
    zoneId: zone_id
