apiVersion: zero.cloudflare.crossplane.io/v1alpha1
kind: TrustOrganization
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustorganization
  labels:
    testing.upbound.io/example-name: example_zero_trust_organization
  name: example-zero-trust-organization
spec:
  forProvider:
    allowAuthenticateViaWarp: true
    authDomain: test.cloudflareaccess.com
    autoRedirectToIdentity: true
    customPages:
      forbidden: 699d98642c564d2e855e9661899b7252
      identityDenied: 699d98642c564d2e855e9661899b7252
    isUiReadOnly: true
    loginDesign:
      backgroundColor: '#c5ed1b'
      footerText: This is an example description.
      headerText: This is an example description.
      logoPath: https://example.com/logo.png
      textColor: '#c5ed1b'
    sessionDuration: 24h
    uiReadOnlyToggleReason: Temporarily turn off the UI read only lock to make a change
      via the UI
    userSeatExpirationInactiveTime: 730h
    warpAuthSessionDuration: 24h
    zoneId: zone_id
