apiVersion: rate.cloudflare.crossplane.io/v1alpha1
kind: Limit
metadata:
  annotations:
    meta.upbound.io/example-id: rate/v1alpha1/limit
  labels:
    testing.upbound.io/example-name: example_rate_limit
  name: example-rate-limit
spec:
  forProvider:
    action:
      mode: simulate
      response:
        body: <error>This request has been rate-limited.</error>
        contentType: text/xml
      timeout: 86400
    match:
      headers:
      - name: Cf-Cache-Status
        op: eq
        value: HIT
      request:
        methods:
        - GET
        - POST
        schemes:
        - HTTP
        - HTTPS
        url: '*.example.org/path*'
      response:
        originTraffic: true
    period: 900
    threshold: 60
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
