apiVersion: access.cloudflare.crossplane.io/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: access/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: example_access_rule
  name: example-access-rule
spec:
  forProvider:
    configuration:
      target: ip
      value: 198.51.100.4
    mode: block
    notes: This rule is enabled because of an event that occurred on date X.
    zoneId: zone_id
