// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConnectorRulesInitParameters struct {

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	Parameters *ParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Attributes List) List of Cloud Connector rules (see below for nested schema)
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ConnectorRulesObservation struct {

	// (String) Cloud Provider type
	// Cloud Provider type
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	Parameters *ParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Attributes List) List of Cloud Connector rules (see below for nested schema)
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ConnectorRulesParameters struct {

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	// +kubebuilder:validation:Optional
	Parameters *ParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (Attributes List) List of Cloud Connector rules (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Identifier
	// Identifier
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ParametersInitParameters struct {
}

type ParametersObservation struct {

	// (String) Host to perform Cloud Connection to
	// Host to perform Cloud Connection to
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ParametersParameters struct {
}

type RulesInitParameters struct {

	// (String) Cloud Provider type
	// Cloud Provider type
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	Parameters *RulesParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type RulesObservation struct {

	// (String) Cloud Provider type
	// Cloud Provider type
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	Parameters *RulesParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type RulesParameters struct {

	// (String) Cloud Provider type
	// Cloud Provider type
	// +kubebuilder:validation:Optional
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Parameters of Cloud Connector Rule (see below for nested schema)
	// +kubebuilder:validation:Optional
	Parameters *RulesParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type RulesParametersInitParameters struct {

	// (String) Host to perform Cloud Connection to
	// Host to perform Cloud Connection to
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type RulesParametersObservation struct {

	// (String) Host to perform Cloud Connection to
	// Host to perform Cloud Connection to
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type RulesParametersParameters struct {

	// (String) Host to perform Cloud Connection to
	// Host to perform Cloud Connection to
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

// ConnectorRulesSpec defines the desired state of ConnectorRules
type ConnectorRulesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConnectorRulesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectorRulesInitParameters `json:"initProvider,omitempty"`
}

// ConnectorRulesStatus defines the observed state of ConnectorRules.
type ConnectorRulesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnectorRulesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectorRules is the Schema for the ConnectorRuless API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare-upjet}
type ConnectorRules struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rules) || (has(self.initProvider) && has(self.initProvider.rules))",message="spec.forProvider.rules is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   ConnectorRulesSpec   `json:"spec"`
	Status ConnectorRulesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectorRulesList contains a list of ConnectorRuless
type ConnectorRulesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectorRules `json:"items"`
}

// Repository type metadata.
var (
	ConnectorRules_Kind             = "ConnectorRules"
	ConnectorRules_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectorRules_Kind}.String()
	ConnectorRules_KindAPIVersion   = ConnectorRules_Kind + "." + CRDGroupVersion.String()
	ConnectorRules_GroupVersionKind = CRDGroupVersion.WithKind(ConnectorRules_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectorRules{}, &ConnectorRulesList{})
}
