apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: example_dns_firewall
  name: example-dns-firewall
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    attackMitigation:
      enabled: true
      onlyWhenUpstreamUnhealthy: false
    deprecateAnyRequests: true
    ecsFallback: false
    maximumCacheTtl: 900
    minimumCacheTtl: 60
    negativeCacheTtl: 900
    ratelimit: 600
    retries: 2
    upstreamIps:
    - 192.0.2.1
    - 198.51.100.1
    - 2001:DB8:100::CF
