apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: ZoneTransfersPeer
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zonetransferspeer
  labels:
    testing.upbound.io/example-name: example_dns_zone_transfers_peer
  name: example-dns-zone-transfers-peer
spec:
  forProvider:
    accountId: 01a7362d577a6c3019a474fd6f485823
