// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SettingsInternalViewInitParameters struct {

	// (String) Identifier
	// Identifier
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (List of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type SettingsInternalViewObservation struct {

	// (String) Identifier
	// Identifier
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) When the view was created.
	// When the view was created.
	CreatedTime *string `json:"createdTime,omitempty" tf:"created_time,omitempty"`

	// (String) Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) When the view was last modified.
	// When the view was last modified.
	ModifiedTime *string `json:"modifiedTime,omitempty" tf:"modified_time,omitempty"`

	// (List of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type SettingsInternalViewParameters struct {

	// (String) Identifier
	// Identifier
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (List of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	// +kubebuilder:validation:Optional
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

// SettingsInternalViewSpec defines the desired state of SettingsInternalView
type SettingsInternalViewSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingsInternalViewParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsInternalViewInitParameters `json:"initProvider,omitempty"`
}

// SettingsInternalViewStatus defines the observed state of SettingsInternalView.
type SettingsInternalViewStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsInternalViewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SettingsInternalView is the Schema for the SettingsInternalViews API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare-upjet}
type SettingsInternalView struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zones) || (has(self.initProvider) && has(self.initProvider.zones))",message="spec.forProvider.zones is a required parameter"
	Spec   SettingsInternalViewSpec   `json:"spec"`
	Status SettingsInternalViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsInternalViewList contains a list of SettingsInternalViews
type SettingsInternalViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SettingsInternalView `json:"items"`
}

// Repository type metadata.
var (
	SettingsInternalView_Kind             = "SettingsInternalView"
	SettingsInternalView_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SettingsInternalView_Kind}.String()
	SettingsInternalView_KindAPIVersion   = SettingsInternalView_Kind + "." + CRDGroupVersion.String()
	SettingsInternalView_GroupVersionKind = CRDGroupVersion.WithKind(SettingsInternalView_Kind)
)

func init() {
	SchemeBuilder.Register(&SettingsInternalView{}, &SettingsInternalViewList{})
}
