apiVersion: leaked.cloudflare.crossplane.io/v1alpha1
kind: CredentialCheckRule
metadata:
  annotations:
    meta.upbound.io/example-id: leaked/v1alpha1/credentialcheckrule
  labels:
    testing.upbound.io/example-name: example_leaked_credential_check_rule
  name: example-leaked-credential-check-rule
spec:
  forProvider:
    password: lookup_json_string(http.request.body.raw, "secret")
    username: lookup_json_string(http.request.body.raw, "user")
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
