apiVersion: workers.cloudflare.crossplane.io/v1alpha1
kind: Script
metadata:
  annotations:
    meta.upbound.io/example-id: workers/v1alpha1/script
  labels:
    testing.upbound.io/example-name: example_workers_script
  name: example-workers-script
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    assets:
      config:
        htmlHandling: auto-trailing-slash
        notFoundHandling: none
        runWorkerFirst: false
        serveDirectly: true
      jwt: jwt
    bindings:
    - name: MY_ENV_VAR
      text: my_data
      type: plain_text
    bodyPart: worker.js
    compatibilityDate: "2021-01-01"
    compatibilityFlags:
    - nodejs_compat
    keepAssets: false
    keepBindings:
    - string
    mainModule: worker.js
    migrations:
      deletedClasses:
      - string
      newClasses:
      - string
      newSqliteClasses:
      - string
      newTag: v2
      oldTag: v1
      renamedClasses:
      - from: from
        to: to
      transferredClasses:
      - from: from
        fromScript: from_script
        to: to
    observability:
      enabled: true
      headSamplingRate: 0.1
    placement:
      mode: smart
    scriptName: this-is_my_script-01
    tags:
    - string
    tailConsumers:
    - environment: production
      namespace: my-namespace
      service: my-log-consumer
