apiVersion: workers.cloudflare.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: workers/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: example_workers_secret
  name: example-workers-secret
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    dispatchNamespace: my-dispatch-namespace
    scriptName: this-is_my_script-01
    text: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    type: secret_text
