apiVersion: page.cloudflare.crossplane.io/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: page/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    actions:
    - emailObfuscation: "on"
      minify:
      - css: "on"
        html: "off"
        js: "on"
      ssl: flexible
    priority: 1
    target: sub.${var.cloudflare_zone}/page
    zoneId: ${var.cloudflare_zone_id}
