apiVersion: snippet.cloudflare.crossplane.io/v1alpha1
kind: Rules
metadata:
  annotations:
    meta.upbound.io/example-id: snippet/v1alpha1/rules
  labels:
    testing.upbound.io/example-name: example_snippet_rules
  name: example-snippet-rules
spec:
  forProvider:
    rules:
    - description: Rule description
      enabled: true
      expression: http.cookie eq "a=b"
      snippetName: snippet_name_01
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
