apiVersion: api.cloudflare.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: api/v1alpha1/token
  labels:
    testing.upbound.io/example-name: example_api_token
  name: example-api-token
spec:
  forProvider:
    condition:
      requestIp:
        in:
        - 123.123.123.0/24
        - 2606:4700::/32
        notIn:
        - 123.123.123.100/24
        - 2606:4700:4700::/48
    expiresOn: "2020-01-01T00:00:00Z"
    notBefore: "2018-07-01T05:20:00Z"
    policies:
    - effect: allow
      permissionGroups:
      - id: c8fed203ed3043cba015a93ad1616f1f
        meta:
          key: key
          value: value
      - id: 82e64a83756745bbbb1c9c2701bf816b
        meta:
          key: key
          value: value
      resources:
        com.cloudflare.api.account.zone.22b1de5f1c0e4b3ea97bb1e963b06a43: '*'
        com.cloudflare.api.account.zone.eb78d65290b24279ba6f44721b3ea3c4: '*'
