apiVersion: email.cloudflare.crossplane.io/v1alpha1
kind: RoutingCatchAll
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/routingcatchall
  labels:
    testing.upbound.io/example-name: example_email_routing_catch_all
  name: example-email-routing-catch-all
spec:
  forProvider:
    actions:
    - type: drop
      value:
      - destinationaddress@example.net
    enabled: true
    matchers:
    - type: all
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
