apiVersion: email.cloudflare.crossplane.io/v1alpha1
kind: RoutingRule
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/routingrule
  labels:
    testing.upbound.io/example-name: example_email_routing_rule
  name: example-email-routing-rule
spec:
  forProvider:
    actions:
    - type: drop
      value:
      - destinationaddress@example.net
    enabled: true
    matchers:
    - field: to
      type: literal
      value: test@example.com
    priority: 0
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
